### ISSUE TITLE
Add `get_milestone_by_id_raw` and `get_milestone_by_index_raw` to MessageInterface for Stardust bindings

### ISSUE THREAD

**Issue by samuel-rufi** [iotaledger-archive/iota.rs#1006]
## Description

Currently the `MessageInterface` doesn't support the `get_milestone_by_id_raw` or `get_milestone_by_index_raw` commands.

## Motivation

Required with latest Stardust changes.

## Are you planning to do it yourself in a pull request?

Yes.

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota.rs/pull/1007
