### ISSUE TITLE
Getting error since latest relase "@iota/iota-rs-wasm": "^1.0.0-alpha.4",

### ISSUE THREAD

**Issue by kuhlmannmarkus** [iotaledger-archive/iota.rs#103]
Since updating to the latest release, I get the following error when including the library:

`Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #53 module="wbg" function="__wbindgen_closure_wrapper1069" error: function import requires a callable`

**Comment by wusyong** [comment]
Could you provide a minimum reproducible example maybe in `bindins/wasm/examples/rollup` or `webpack`? But yeah, we should update the version to address the typo fix.

**Comment by kuhlmannmarkus** [comment]
Error was on my side, sorry!
