### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#105]
https://github.com/iotaledger/iota.rs/blob/37dca441418a9da2d8c045da381e2e3ef29c40ca/iota-client/client.rs#L318
I think the warning was used in the other libs because they also checked if there is an transaction on an address (also without value)

This lib only checks for balance and if an address was used for an outgoing value tx and both things are stored independent of snapshots/pruning

**Comment by wusyong** [comment]
You're right. Let me remove for now.
