### ISSUE TITLE
Node.js bindings stardust documentation

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger-archive/iota.rs#1098]
- [ ] Getting started
    - [x] Setup
    - [ ] Message Interface
    - [x] API Reference
- [x] Guides / examples
    - [x] Get node info
    - [x] Build outputs
    - [x] Get outputs
    - [x] Generate mnemonic
    - [x] Generate addresses
    - [x] Create blocks
    - [x] Post blocks
    - [x] Get blocks
    - [x] Prepare & sign transactions

**Comment by Thoralf-M** [comment]
https://github.com/iotaledger/iota.rs/commit/4c3b71b13d16ea543434ef2e652734f9d79c30b0
