### ISSUE TITLE
Revisit the naming of PoW fields in Rust Config/ConfigBuilder

### ISSUE THREAD

**Issue by samuel-rufi** [iotaledger-archive/iota.rs#1156]
## Description

It seems like some fields are named "PoW" while others are named "Pow". These inconsistencies need to be fixed.

**Comment by Thoralf-M** [comment]
Should be aligned with https://github.com/iotaledger/bee/pull/1481

**Comment by Thoralf-M** [comment]
Done in https://github.com/iotaledger/iota.rs/pull/1163
