### ISSUE TITLE
Port protocol parameters getter(s) to the bindings

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger-archive/iota.rs#1281]
## Description
It would be useful to have equivalents of these methods from the Rust library
```
Client::get_token_supply(&self) -> Result<u64>;
Client::get_protocol_parameters -> Result<ProtocolParameters>; 
```
ported to the bindings (at least from what I could tell they do not exist in Nodejs and Python as of now). 

## Motivation
In identity.rs we need a way for our JS users to obtain these parameters so they can pass them in to our library (which then uses them when calling functionality from say `bee::block` etc.). Note that our Wasm bindings to this library is currently based on a fork where we may implement this ourselves, but it would be better to collaborate on an approach that can work for all the bindings of `iota-client`. 

## Are you planning to do it yourself in a pull request?
I am happy to help, but it may take some time since I have not contributed to this code base before.

**Comment by Thoralf-M** [comment]
Would https://github.com/iotaledger/iota.rs/pull/1282 be enough for you? From the network info you can get these values

**Comment by olivereanderson** [comment]
> Would https://github.com/iotaledger/iota.rs/pull/1282 be enough for you? From the network info you can get these values 

@Thoralf-M  I think that might be enough for us yes. If this can get merged very soon that would be optimal for us :+1:

**Comment by olivereanderson** [comment]
It would however be more convenient to also have the methods requested in this PR specifically.

**Comment by olivereanderson** [comment]
This is most likely blocked on https://github.com/iotaledger/iota.rs/issues/1283.
