### ISSUE TITLE
[Bug]: `block_on` causes panic in Wasm

### ISSUE THREAD

**Issue by PhilippGackstatter** [iotaledger-archive/iota.rs#1283]
### Issue description

Using `futures::executor::block_on` when compiling to Wasm panics. This [reddit thread](https://www.reddit.com/r/rust/comments/srtrbz/wasm_panicked_at_condvar_wait_not_supported/) is where I take that "block_on panics on Wasm" from, which we can replicate in nodejs, too.

### Version

2.0.1-rc.1

### Expected behaviour

No panic.

### Actual behaviour

```
panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/locks/condvar.rs:21:9
```

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Using `block_on` panics when the first `Future` returns `Pending`. This happens somewhere in `reqwest`. For easier reproducibility, change the Wasm specific block in `get_network_info` with:
```rust
#[cfg(target_family = "wasm")]
  {
      futures::executor::block_on({ 
          futures::future::pending::<()>()
       });
  }
```
2. Check out https://github.com/iotaledger/iota.rs-wasm/tree/feat/rewrite-wasm-bindings/bindings/wasm.
3. `npm run build:nodejs`
4. Write a test file in the root of the bindings, that calls the function, e.g.
```typescript
import { Client } from "./node"

async function test() {
  const client = new Client({
    primaryNode: "http://localhost:14265",
    localPow: true,
  });

  await client.getNetworkInfo();
}

test()
```
5. Execute.
```panicked at 'condvar wait not supported', library/std/src/sys/wasm/../unsupported/locks/condvar.rs:21:9```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olivereanderson** [comment]
We have a hacky solution working on our fork now, so perhaps not ultra urgent anymore. This is also mainly a wasm issue which `iota.rs` does not support as of now. We will however be very grateful for a proper fix :+1:

**Comment by thibault-martinez** [comment]
> We have a hacky solution working on our fork now, so perhaps not ultra urgent anymore. This is also mainly a wasm issue which `iota.rs` does not support as of now. We will however be very grateful for a proper fix 👍

As of curiosity, what's the hacky solution?

**Comment by PhilippGackstatter** [comment]
It's basically make the builder async and fetch the params once at startup, plus add a method so users can fetch them on demand later. Pretty horrible overall, but we had to get something working.
https://github.com/iotaledger/iota.rs-wasm/blob/a706a76eae5572788a3dc34a8f59c6dc4d92a41a/src/client/builder.rs#L319-L337

**Comment by thibault-martinez** [comment]
Hi @PhilippGackstatter @olivereanderson, have you been able to verify that this specific issue has been fixed? Let us know if we can help, thanks.

**Comment by olivereanderson** [comment]
From my tests it seems to work now. Thank you very much for handling this :+1:  

Now we are waiting for https://github.com/iotaledger/iota.rs/issues/1353 and if everything works once that is fixed we can open up a Wasm bindings PR.
