### ISSUE TITLE
[Bug]: `OutputResponse` is missing the raw bytes response

### ISSUE THREAD

**Issue by grtlr** [iotaledger-archive/iota.rs#1317]
### Issue description

According to the Core API TIP the `/api/core/v2/outputs/{outputId}` endpoint should return raw bytes in addition to JSON.

### Version

`iota-types:1.0.0-rc`

### Expected behaviour

`OutputResponse` should follow the TIP.

### Actual behaviour

It does not :trollface: 

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
There is `get_output_raw()`, the raw output shouldn't be there additionally, it depends on the header you send

**Comment by grtlr** [comment]
I don't think I fully understand. Here is the definition of `BlockResponse`:
```rust
/// Response of GET /api/core/v2/blocks/{block_id}.
/// Returns a specific block.
#[derive(Clone, Debug, Eq, PartialEq)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(rename_all = "camelCase"),
    serde(untagged)
)]
pub enum BlockResponse {
    Json(BlockDto),
    Raw(Vec<u8>),
}
```

The definition of `OutputResponse` looks as follows:
```rust
/// Response of GET /api/core/v2/outputs/{output_id}.
/// Returns an output and its metadata.
#[derive(Clone, Debug, Eq, PartialEq)]
#[cfg_attr(
    feature = "serde",
    derive(serde::Serialize, serde::Deserialize),
    serde(rename_all = "camelCase")
)]
pub struct OutputResponse {
    pub metadata: OutputMetadataResponse,
    pub output: OutputDto,
}
```

The response of the call depends on the header (`application/vnd.iota.serializer-v1`), but the response type should be able to represent both repsonse variants just like `BlockResponse` and `MilestoneResponse`.
