### ISSUE TITLE
[Bug]: `INodeInfoProtocol` fails to deserialize to `ProtocolParameters`

### ISSUE THREAD

**Issue by olivereanderson** [iotaledger-archive/iota.rs#1353]
### Issue description

The type  [`INodeInfoProtocol`](https://github.com/iotaledger/iota.js/blob/feat/stardust/packages/iota/src/models/info/INodeInfoProtocol.ts#L8) returned from  [`Client.getProtocolParameters`](https://github.com/iotaledger/iota.rs/blob/develop/client/bindings/nodejs/lib/Client.ts#L435) fails to deserialize into [`ProtocolParameters`](https://github.com/iotaledger/iota.rs/blob/develop/types/src/block/protocol.rs#L19) which is returned from the [equivalent Rust native method](https://github.com/iotaledger/iota.rs/blob/develop/client/src/client/mod.rs#L138).

I am not sure whether this should be considered a bug or a request to make the two representations more alike. Either way it would be great if the library could provide a mechanism to easily convert between the two (which we would then use in [identity.rs](https://github.com/iotaledger/identity.rs)). 

### Version

branch: develop (commit: d7bc22f7fed96d8d1283b335bfaac80f02602e11). 

### Expected behaviour

I expected deserialization between types produced by the bindings and the Rust equivalents to work out of the box. 
In other words this should not panic:
```
   let protocol_parameters: ProtocolParameters = <INodeInfoProtocol as wasm_bindgen::JsValue>::into_serde(&js_parameters).unwrap();  
```

### Actual behaviour

Panics because of incompatibility of `string` used in JS to represent (`NetworkName` and `Bech32Hrp`) with `StringPrefix` used in Rust. 

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. Initialize an instance of `INodeInfoProtocol` (for instance by calling the `getProtocolParameters` method on the client). 
2. log a json representation of the instance created in step 1. 
3. Create the following Rust program:
```
use std::error::Error;
use iota_client::block::protocol::ProtocolParameters;

fn main() -> Result<(),Box<dyn Error>>{
    let json: &str = r#"<paste the json from step 2 here>"#;
    let protocol_parameters: Result<ProtocolParameters,_> = serde_json::from_str(json);
    protocol_parameters.map(|parameters| println!("{:#?}", parameters)).map_err(Into::into)
}
```

### Errors

When 
```    
json = r#"{
        "version":2,
        "networkName":"testnet",
        "bech32Hrp":"rms",
        "minPowScore":1500,
        "belowMaxDepth":15,
        "rentStructure":{"vByteCost":100,"vByteFactorKey":10,"vByteFactorData":1},
        "tokenSupply":"1450896407249092"
        }"#; 
```
I get the following error under `cargo run`: 
```
Error: Error("invalid type: string \"testnet\", expected struct StringPrefix", line: 3, column: 31)
```

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota.rs/pull/1391
