### ISSUE TITLE
[Task]: Remove `.with_node_sync_disabled()` from examples

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#1370]
### Task description

Remove `.with_node_sync_disabled()` from examples as it shouldn't be necessary and should only be used in special cases if a node isn't healthy 

### Requirements

-

### Acceptance criteria

-

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by arne-fuchs** [comment]
What about renaming the function? As discussed in discord the function doesn't does still sync with the node even when calling the function.
Might rename it to something like ignore_health_status() and mark with_node_sync_disabled() depricated but calling ignore_health_status() to support older versions.
Edit: I have just seen https://github.com/iotaledger/iota.rs/pull/1372
