### ISSUE TITLE
local time X doesn't match the time of the latest milestone timestamp: Y

### ISSUE THREAD

**Issue by thibault-martinez** [iotaledger-archive/iota.rs#1385]
> Additionally, occasionally I get this util I refresh the app when trying to send a transaction:
local time 1668605691 doesn't match the time of the latest milestone timestamp: 1668605338
Which is a really small time interval to be concerned about?

> Although we are getting this error after successfully sending one NFT and then trying to send another

**Comment by Thoralf-M** [comment]
Tested some things and I think syncing an account in wallet.rs somehow blocked or completely stopped the node syncing process
Unfortunately I couldn't reproduce it in a reliable way

**Comment by thibault-martinez** [comment]
Closed by https://github.com/iotaledger/iota.rs/pull/1425

**Comment by KtxKtx** [comment]
Hello, i got this bug today. I have bought some IOTA in 2021/2022 and installed Firefly today again. Ned urgent help, need login for TaxReport ! @thibault-martinez

**Comment by Thoralf-M** [comment]
@KtxKtx please make sure that your system time is synced, because this bug should be fixed.
If you use Windows you can do it as explained here https://www.majorgeeks.com/content/page/synchronize_clock_with_an_internet_time_server.html

**Comment by gasparyan077** [comment]
Hi, last time I opened my firefly wallet a year ago. Today I backed up via stronghold file and uploaded on my another pc. But it says that "local time 1709370477 doesn't match the time of the latest milestone timestamp 1709374437. Please, advice

**Comment by KtxKtx** [comment]
Hi, correct it was the wrong time. I installed Ubuntu or something and my system clock had the wrong time setup. thx

> @KtxKtx please make sure that your system time is synced, because this bug should be fixed. If you use Windows you can do it as explained here https://www.majorgeeks.com/content/page/synchronize_clock_with_an_internet_time_server.html


> Hi, last time I opened my firefly wallet a year ago. Today I backed up via stronghold file and uploaded on my another pc. But it says that "local time 1709370477 doesn't match the time of the latest milestone timestamp 1709374437. Please, advice
