### ISSUE TITLE
[Task]: Add proper tags to npm package

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger-archive/iota.rs#1403]
### Task description

We should tag the IOTA version with `latest` and Shimmer with `Staging` or similar. Maybe even `Shimmer` :think

### Requirements

- Change tag of published packages

### Acceptance criteria

Both IOTA and Shimmer have the correct tag and can be installed with 
`npm i @iota/client`
or
`npm i @iota/client@staging`

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by Thoralf-M** [comment]
But then we can end up with two npm packages that have exactly the same? For example when stardust is on mainnet and we don't have something new for shimmer

**Comment by Dr-Electron** [comment]
Is that a problem?

**Comment by Thoralf-M** [comment]
I misunderstood, I thought it would create two separated npm packages, but the tag is just added to the version, so should be fine
