### ISSUE TITLE
Bug: Infinite loop in async call (pre-chrysalis)

### ISSUE THREAD

**Issue by kwek20** [iotaledger-archive/iota.rs#146]
Streams team is experiencing an issue where using the iota.rs library call `send` hangs forever
https://github.com/iotaledger/iota.rs/blob/iota-1.0/iota-client/src/client.rs#L28
It seems like the issue is in `reqwest` or `smol` after a quick investigation, but this is unconfirmed.

If you want to recreate the issue all you need to do is:
Clone `https://github.com/iot2tangle/Streams-http-gateway`, and `cargo run --release` This will give you a channel root in the terminal, take that and put it to the side for now.

Send the curl command they have in their readme and run it 30-40 times to put some data into the channel
Clone `https://github.com/iot2tangle/Example-streams-subscriber` and `cargo run --release [channel root here]`

It will find just over 20 of the messages, and then it hangs
When we breakpoint our way through the process, we found that it was hanging on the `findTransactions` or `getTrytes` call from the iota.rs side while it uses the `response!` macro. Since it does this, and we await the response, our streams subscriber instance stalls out, and then so does the `Example-Streams-Subscriber`.
Because it doesn't return an error or an actual response, it's stuck awaiting forever

So the workaround we are thinking of applying is to timeout our calls to the client so that if it hangs, we can kill the call and return a timeout error on our end, as we've already tried adding a timeout into the client library itself, but it feels like it's just putting a bandaid on a potentially critical problem. On our end we do not utilize the async calls asynchronously, we await each one

We have tested this with different nodes.

Actual findings: (Dyrell)
24 successful rounds of 5 calls (4 find transactions and 1 get tryte)
then fails on the 4/5 call every time on the 25th round (so 124 seems to mean something?)

After inspecting network traffic with wireshark:
Red: Streams instance calls, Blue: Node responses
Small Responses: findTransactions, Big responses: getTrytes
PDF with data: [packets.pdf](https://github.com/iotaledger/iota.rs/files/5440571/packets.pdf)
**Explanation**: All requests have a response, then the very last message (1124) is the `FIN` packet we send as there's no more connection (FIN ACK wasnt caught). Findings: All requests are send and we receive responses)

---
Actual findings: (Brord)
**Example**: Run the following in `Example-streams-subscriber`: `cargo run --release 85f4e5ceedbab180cc7b2f117b86eaac2cf113b1a73d17bf90de1e44d7464c690000000000000000:b0a612fce2b888182963e792`

It will stall out after receiving 17 messages, when fetching the data of the 18th. It finds the hash and then continues to call `get_trytes`, on which it stalls forever. (https://github.com/iotaledger/iota.rs/blob/iota-1.0/iota-client/src/client.rs#L342)

To clarify; it goes into our `get_bundles` method, does `find_transactions`, goes through `handle_client_result`, and passes the `ensure!`. Then it calls `get_trytes` and we wait forever.
streams `get_bundles` method: https://github.com/iotaledger/streams/blob/develop/iota-streams-app/src/transport/tangle/client.rs#L323

(Before sending the 18th message, it stalled on `find_transactions` in `get_bundles`, the second attempt. First time resulted in empty (no message), second one stalls)

**Comment by kwek20** [comment]
Maybe related: https://github.com/seanmonstar/reqwest/issues/1054

**Comment by wusyong** [comment]
@kwek20 Thanks for the report! I tested it with debugger and found it got stuck too. Sine `iota-1.0` is sort of a archived branch, I don't want to bring too much breaking changes of it. What I could offer is change to blocking library but still providing the same async function signatures. So all you need to do is updating the dependency of `iota-core` in your cargo.toml. 

I have pushed the change and saw it could receive 40+ messages in `Example-streams-subscriber` repo. Could you also help testing it to confirm that?

**Comment by Meph1587** [comment]
Hey Guys, looks like it's working now, I tested it on and managed to send a lot (din't count) of messages and receive them in real-time form the example-subscriber : )

**Comment by kwek20** [comment]
@wusyong Yea i tested it and this works! Thank you!
