### ISSUE TITLE
How to get the balance by address?

### ISSUE THREAD

**Issue by christopher-wilke** [iotaledger-archive/iota.rs#1463]
How do I get the balance by an address? I found an example with a [SecretManager](https://github.com/iotaledger/iota.rs/blob/develop/client/examples/02_get_address_balance.rs) but I really just need the balance and I dont want to create a `SecretManager` for this use case.

Balance for addresses were supported on [V 1.3.0](https://docs.rs/iota-client/latest/iota_client/client/struct.Client.html#method.get_address_balances).

**Comment by Thoralf-M** [comment]
There isn't a clear definition for what the balance is with the new outputs and unlock conditions, but we have an example which gets the basic outputs with address unlock condition alone and returns the amount + native tokens: https://github.com/iotaledger/iota.rs/blob/6f6b05937ee4c0d85768bc8fafb9ec8648b7cfce/client/examples/02_get_address_balance.rs#L40-L70
Other output types and outputs with other unlock conditions might be also part of what you understand under balance, so they would then need to be requested and processed also

**Comment by christopher-wilke** [comment]
Thanks @thibault-martinez, worked as expected.
