### ISSUE TITLE
[Bug]:nodejs @iota/client, can't buildAndPostBlock After local build on raspberry

### ISSUE THREAD

**Issue by mahermeg17** [iotaledger-archive/iota.rs#1493]
### Issue description

After local build on raspberry of the @iota/client nodejs lib, I can't use client.buildAndPostBlock to send a block to a private tangle.
But when using the shimmer test network it works.
And even getInfo() works with the private tangle
And when testing with ubuntu client (npm install @iota/client), I can write a block on the private tangle.
So, the only use case where it blocks is when sending data blocks from the built client to the private tangle.

### Version

@iota/client : 3.0.0-rc.5
HORNET : 2.0.0-rc.4

### Expected behaviour

The locally built @iota/client should write a block on the private tangle.

### Actual behaviour

The code freezes when executing 
```
// Create block with tagged payload
        const blockIdAndBlock = await client.buildAndPostBlock(
            secretManager,
            options,
        );
```
no error, no fail. just waiting.

### Can the issue reliably be reproduced?

Yes

### Steps to reproduce the issue

1. build @iota/client on arm64
2. run a private tangle
3. create a new node project
4. use the sample [08_data_block.ts](https://github.com/iotaledger/iota.rs/blob/develop/client/bindings/nodejs/examples/08_data_block.ts)

### Errors

The code freezes without any error message.

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
@mahermeg17 do you have the min PoW score set to 0 in the private tangle? Then it should be fixed by https://github.com/iotaledger/iota.rs/pull/1476, we will do a new release with this fix included ASAP

**Comment by Thoralf-M** [comment]
@mahermeg17 `@iota/client@3.0.0-rc.6`  has this fix and is released, binaries are still being built https://github.com/iotaledger/iota.rs/actions/runs/3942083917/jobs/6745306723

**Comment by mahermeg17** [comment]
Thank you @Thoralf-M . That's it. It works fine after the #1476 fix.
But what I find curious is that before fixing the problem, writing to the shimmer testnet is fine. Only writing to the private tangle shows problem.

**Comment by Thoralf-M** [comment]
The problem was that it was only an infinite loop if the nonce was 0, which is enough in your private tangle if the min pow score is 0
For the testnet the min pow score is not 0, so 0 as nonce is also not valid

**Comment by mahermeg17** [comment]
OK. I see. thank you.
