### ISSUE TITLE
Implementation of retry, reattach & promote methods

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#151]
The library currently misses the implementation of the following methods:

- [retry()](https://github.com/laumair/iota.rs/blob/chore/retry-method-spec/specs/iota-rs-ENGINEERING-SPEC-0000.md#retry);
- [reattach()](https://github.com/laumair/iota.rs/blob/chore/retry-method-spec/specs/iota-rs-ENGINEERING-SPEC-0000.md#reattach);
- [promote()](https://github.com/laumair/iota.rs/blob/chore/retry-method-spec/specs/iota-rs-ENGINEERING-SPEC-0000.md#promote).

The implementation details are added to the specification document. For a reference implementation, see:

- Determining if a message needs promotion or reattachment https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/libs/iota/transfers.js#L99-L139;
- How to reattach https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/libs/iota/extendedApi.js#L299-L332;
- How to promote https://github.com/iotaledger/trinity-wallet/blob/develop/src/shared/libs/iota/extendedApi.js#L211-L247.

Related: https://github.com/iotaledger/iota.rs/pull/150

/cc @cvarley100 @fijter @bingyanglin @wusyong

**Comment by bingyanglin** [comment]
Fixed in #161
