### ISSUE TITLE
Why does finish_output need a token supply?

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger-archive/iota.rs#1592]
## Description

In all examples to create outputs I first need to get the token supply. But why? This should be part of an internal call, but why does the developer need to know the token supply?

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
It's required for the output validation, can't be done internally because you don't provide the client to the builder

If you don't care about it being valid you can use `.finish_unverified()`

**Comment by Dr-Electron** [comment]
I See. I still find it ugly tho 😅.
But I guess there is no (nicer) way around that?

**Comment by thibault-martinez** [comment]
See it as what it is, a protocol parameter. `finish_output` is pretty low in the stack and requires it. A wallet user doesn't care about that kind of things but a client user does.

**Comment by Dr-Electron** [comment]
I See the reasoning in this being a low level library. But still it feels weird. Because as a dev who uses the library I still don't care about this. If I use the library with a network, the token supply will always be defined and I will never think about the needed validation for it 🤔 

But I see your point and will close the issue 👍

**Comment by Thoralf-M** [comment]
> If I use the library with a network, the token supply will always be defined and I will never think about the needed validation for it

But where would the validation then happen? Only when you send it to the node?
