### ISSUE TITLE
Node.js run how tos is missing some details

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger-archive/iota.rs#1595]
## Description

In https://wiki.iota.org/shimmer/iota.rs/how_tos/run_how_tos/ we explain that you need to follow the [Getting Started](https://wiki.iota.org/shimmer/iota.rs/how_tos/getting_started/nodejs/) guide. Although that's not correct. 
I have to install the examples with `npm i`.

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Added in https://github.com/iotaledger/iota.rs/commit/b2bb4a11b7d4bce7009c37972072f00b7818f86a
