### ISSUE TITLE
Unify "Build an Alias Output" example

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger-archive/iota.rs#1610]
## Description

The [Build an Alias Output](https://wiki.iota.org/shimmer/iota.rs/how_tos/build_alias_output/) examples explain different features in different languages.
This issue is part of the efforts in iotaledger/iota-sdk#59 

## Motivation

We should show/explain the same features in all languages (if they exist).

## Requirements

Let's show in every example how to:

- [ ] Remove unneeded content of how to create a secret manager or addresses.
    - [ ] Rust
    - [ ] Nodejs
    - [x] Python
    - [ ] Java 
- [ ] Add how to create second transition to bindings (See open question)

## Open questions (optional)

As in the foundry example the how to create a second transaction should probably be its own how to inside of the Alias output section of something. But again I think its nice to have that guides for all bindings first and we can split up later 🤔 

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
>  how to create a second transaction

What kind of transaction should this be?

**Comment by Dr-Electron** [comment]
The state transition from the rust example. Just for the bindings

**Comment by Thoralf-M** [comment]
But then you need a secret manager again and the example does much more

**Comment by Dr-Electron** [comment]
Ser, when read my issues? :trollface: 
> But again I think its nice to have that guides for all bindings first and we can split up later 🤔

I think it is worth it. Because in the next sprint everyone could just split up the examples. We don't need to ask you and can help out as all info we need is provided 🤔 

So temporary this may make the how-tos "worse", but makes it easier to "fix" them later

**Comment by Thoralf-M** [comment]
> Ser, when read my issues? :trollface:

`[ ] Remove unneeded content of how to create a secret manager or addresses.`

Instructions unclear, closing issue :trollface:
