### ISSUE TITLE
Remove iota-crypto/keccak.rs and replace it with the original tiny-keccak crate

### ISSUE THREAD

**Issue by SuperFluffy** [iotaledger-archive/iota.rs#20]
It looks like `iota-crypto/keccak.rs` was lifted verbatim from the [`tiny-keccak` crate](https://github.com/debris/tiny-keccak/blob/master/src/lib.rs). It ssems like this is okay under its very permissive `CC0-1.0` license, but still not good style.

We should replace the code and link `tiny-keccak` directly for proper attribution.

**Comment by njaremko** [comment]
A quick git diff of their version and ours would show you that that is not true. This repo contains changes to visibility that were required for implementing Iota's PoW (if I recall correctly)

**Comment by SuperFluffy** [comment]
Well, let's fork it then and add the changes on top. Or keep in the repo and clean it up to at least document the changes. My main concern is not with the functionality but with attribution.

**Comment by njaremko** [comment]
If your issue is with attribution, then no change is needed, as it is explicitly attributed to both Marek Kotewicz and David Leon Gil.
