### ISSUE TITLE
The `get_network_info` API should fail if no synced node are available

### ISSUE THREAD

**Issue by lucasfernog** [iotaledger-archive/iota.rs#310]
On the wallet.rs i'm using the `get_network_info` API to get the bech32 HRP for my addresses. When the node isn't synced, it returns the default NetworkInfo object. IMO that's wrong, because it leads me to save invalid addresses for the network.

Maybe the default object should instead be `None`, filled by the `sync` process and by the `get_network_info` API itself if it finds that the info is empty.

**Comment by Thoralf-M** [comment]
Just like `network_id`?

**Comment by Thoralf-M** [comment]
When it get's updated it should also only be modified when it's not already set (network_id especially, because then we don't need to do the hashing each time)
