### ISSUE TITLE
Using the iota_client.dll with Python

### ISSUE THREAD

**Issue by huggre** [iotaledger-archive/iota.rs#364]
Hi, wanted to test the new iota.rs library with Python on my Windows PC.
I was able to build the iota_client.dll but how do I import and use it in my Python script?
A small example would be nice.
Thanks

**Comment by Thoralf-M** [comment]
There is this example here https://github.com/iotaledger/iota.rs/blob/dev/bindings/python/examples/example.py, you just need to put the .dll file in the same folder

**Comment by huggre** [comment]
Yea, that what I was thinking, however I keep getting this error when running the example.py
ModuleNotFoundError: No module named 'iota_client'
Note! There is already a file in this folder named iota_client.so

**Comment by Thoralf-M** [comment]
Sry, you need to put the .dll file in the folder, but rename it to `.pyd`

**Comment by huggre** [comment]
Thanks Thoralf, now I get this message:
**ImportError: DLL load failed: The specified module could not be found.**
Any idea?

**Comment by Thoralf-M** [comment]
Did you copy the correct .dll file?
bingyanglin added an action to prebuild the files, maybe that's easier for you
https://github.com/iotaledger/iota.rs/tree/dev/bindings/python

**Comment by huggre** [comment]
Will check out the prebuild files, thanks
