### ISSUE TITLE
Support for username and password in node / client options

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#379]
The node / client options should support `username` and `password` for each node. The `node` field will need to accept additional properties to support this. 

References:

- [wallet.rs spec](https://github.com/iotaledger/wallet.rs/blob/develop/specs/wallet-ENGINEERING-SPEC-0000.md#node);
- [JS implementation](https://github.com/iotaledger/iota.js/blob/chrysalis/src/clients/singleNodeClient.ts#L99-L118)

**Comment by Thoralf-M** [comment]
I added it like this, is this fine for you?
https://github.com/iotaledger/iota.rs/blob/2f5941d0187dee1a20e6f4889e6d3ae813d8a2cf/examples/nodeinfo.rs#L12

**Comment by laumair** [comment]
@Thoralf-M Perfect, thank you.
