### ISSUE TITLE
mqtt message parsing shouldn't panic

### ISSUE THREAD

**Issue by lucasfernog** [iotaledger-archive/iota.rs#380]
The code on `get_node_info` has a `.unwrap()` here: https://github.com/iotaledger/iota.rs/blob/815a6271b50251b41b6bc94377075dcc2a0e56b5/iota-client/src/client.rs#L490
It should propagate the error instead, since the function already returns a Result. We should also check if there's other cases of it.

**Comment by Thoralf-M** [comment]
It's removed in https://github.com/iotaledger/iota.rs/pull/373/files

**Comment by Thoralf-M** [comment]
We have unwraps in the mqtt part where we don't return a result, should we ignore possible errors there so it doesn't crash?

**Comment by lucasfernog** [comment]
Yeah I believe we should ignore errors on the mqtt message parsing.

**Comment by lucasfernog** [comment]
Or at least `log::error` them instead.

**Comment by Thoralf-M** [comment]
Related to https://github.com/iotaledger/iota.rs/issues/399
