### ISSUE TITLE
Refactor errors

### ISSUE THREAD

**Issue by melatron** [iotaledger-archive/iota.rs#400]
1. Start using `#[from]` on `bee_message::Error` and `crypto::Error`.
2. Consider using an `&'static str` instead of `String` on error variants (like `MissingParameter`) when value will always be static.
3. Change the wrong documentation on error `TangleInclusionError`.
4. Change the wrong doc on error `ReqwestError`.
5. Change the wrong doc of `NoNeedPromoteOrReattach` - error says "can't" but error is "doesn't need".
6. SQLite storage_err is inconsistently used - Some error still use `.map_err(|_| crate::Error::Storage`
7. `error.rs` should be localizable (translated) in case errors bubble up to any user interface.

**Comment by Thoralf-M** [comment]
8. Embed the actual number of parents in InvalidParentsAmount, useful for debugging purpose

**Comment by Thoralf-M** [comment]
crypto.rs error https://github.com/iotaledger/crypto.rs/pull/64/files
