### ISSUE TITLE
Download links for pre-built Python libs not working

### ISSUE THREAD

**Issue by huggre** [iotaledger-archive/iota.rs#436]
Hi, trying to download the pre-built Python libs but links not working

See links under section 3
https://github.com/iotaledger/iota.rs/tree/dev/bindings/python

**Comment by huggre** [comment]
Hmm, now it suddenly works, closing issue

**Comment by Thoralf-M** [comment]
@huggre use the links from here https://github.com/iotaledger/iota.rs/pull/435/files, the ones in dev branch are outdated until this PR gets merged
