### ISSUE TITLE
[Task]: API Responses need to be validated in test cases. 

### ISSUE THREAD

**Issue by oopsmonk** [iotaledger-archive/iota.rs#44]
The API responses are not validated in test cases. Tests should make sure responses are in the expectation.

**Comment by wusyong** [comment]
There will be various responses on different timing/network. That's why I unwrap most of them atm. It won't panic if they do receive responses from the node.  It's difficult to cover all the situations imho.

**Comment by oopsmonk** [comment]
it doesn't mean to cover all responses from the node but expected responses. for instance, the milestone should not be an empty hash in the getNodeInfo response from a healthy node. some fields have reasonable value and predictable in a response. you can check out what are reasonable responses in https://github.com/iotaledger/iota.c/tree/master/cclient/api/tests

**Comment by thibault-martinez** [comment]
Syntax is already validated by `bee-rest-types`.
The rest will be superseded by https://github.com/iotaledger/iota.rs/issues/1199.
