### ISSUE TITLE
Support wasm32

### ISSUE THREAD

**Issue by l1h3r** [iotaledger-archive/iota.rs#444]
## Description

Add support for compiling iota.rs for `wasm32`-based targets

## Motivation

Needed for identity.rs wasm bindings as iota.rs is used as the client

## Requirements

1. Add feature for node syncing and allow compiling without `tokio`
2. Use feature for explicitly using remote PoW and not spawn threads

## Open questions (optional)

Use this section to ask any questions that are related to the feature.

## Are you planning to do it yourself in a pull request?

No

**Comment by l1h3r** [comment]
@Thoralf-M 🙏 😛

**Comment by Thoralf-M** [comment]
Currently working with this branch https://github.com/iotaledger/iota.rs/tree/chrysalis/wasm, when the node manager PR is merged I will create a PR to have a feature in the dev branch
