### ISSUE TITLE
Add node url to the get_info() endpoint

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#445]
## Description

Add `node` property to the response object of `get_info()`. 

## Motivation

Since iota.rs supports multiple nodes, the node it actually queries under the hood is unknown to the caller. It would be helpful if along with the info `node` url is also returned as part of the response object. That way, it will be helpful for the caller to know which node was actually queried for info. 

## Requirements

Add `node` property to the response object with the URL of the node that was queried. 

## Open questions (optional)

N/A

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
We also have `get_node_info(url: &str)` if you want it for a specific node, do you want it anyways?

**Comment by laumair** [comment]
@Thoralf-M Problem is with multiple nodes, it won't be possible for us to know which node the iota.rs actually used. Therefore, this would be helpful.
