### ISSUE TITLE
get_node_info doesn't work with hornet

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#47]
```RUST
use iota_client;

fn main() {
  println!("{:#?}", iota_client::get_node_info("https://nodes.comnet.thetangle.org".to_string()).unwrap());
}
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Json(Error("missing field `appName`", line: 1, column: 80)))', C:\Users\Boss\.cargo\registry\src\github.com-1ecc6299db9ec823\iota-client-0.1.0\lib.rs:272:44

**Comment by wusyong** [comment]
I tried to test on a hornet node and it worked. Could you test on get-node-info example with your node? (Or DM yours, I can help testing.)

```
GetNodeInfoResponse {
    app_name: "HORNET",
    app_version: "0.4.0-rc8",
    jre_available_processors: None,
    jre_free_memory: None,
    jre_max_memory: None,
    jre_total_memory: None,
    jre_version: None,
    latest_milestone: "HF9ZIOOGOPZLQSEIRUHMTFMBCCQTGOLHFUCSHDEDAOUURFUFSDXKOKPNNEJGSCRAOIUQRQPUYPVGZ9999",
    latest_milestone_index: 1399405,
    latest_solid_subtangle_milestone: "HF9ZIOOGOPZLQSEIRUHMTFMBCCQTGOLHFUCSHDEDAOUURFUFSDXKOKPNNEJGSCRAOIUQRQPUYPVGZ9999",
    latest_solid_subtangle_milestone_index: 1399405,
    milestone_start_index: 1392635,
    neighbors: 7,
    packets_queue_size: None,
    time: 1588517203000,
    tips: 0,
    transactions_to_request: 0,
}
```

**Comment by wusyong** [comment]
Ah just note that new update is not available on crates.io yet. Since bee crates haven't pushed to there. I'm unable to push either. You might want to import current library with git dependency.
```
iota-client = { git = "https://github.com/iotaledger/iota.rs" }
```

**Comment by Thoralf-M** [comment]
https://github.com/wusyong/iota-example/blob/master/src/main.rs works with the new version
