### ISSUE TITLE
Node.js "Getting Started" documentation

### ISSUE THREAD

**Issue by arnoldbird** [iotaledger-archive/iota.rs#483]
At https://client-lib.docs.iota.org/libraries/nodejs/getting_started.html

When I run `npm i @iota/client` I get...

```
$ npm i @iota/client

> @iota/client@0.3.0 install /home/ryan/chrys/node_modules/@iota/client
> prebuild-install --tag-prefix nodejs-binding-v || npm run rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.10.0 runtime=node arch=x64 libc= platform=linux)

> @iota/client@0.3.0 rebuild /home/ryan/chrys/node_modules/@iota/client
> npm run build:neon && node scripts/strip.js


> @iota/client@0.3.0 build:neon /home/ryan/chrys/node_modules/@iota/client
> neon build --release && node scripts/move-lib.js

/home/ryan/chrys/node_modules/neon-cli/lib/ops/neon_new.js:44
const { readFile, stat } = fs_1.promises;
        ^

TypeError: Cannot destructure property `readFile` of 'undefined' or 'null'.
    at Object.<anonymous> (/home/ryan/chrys/node_modules/neon-cli/lib/ops/neon_new.js:44:33)

```

**Comment by Thoralf-M** [comment]
You're using nodejs 8, which is outdated
We currently support nodejs 10.x, 12.x and 14.x

**Comment by arnoldbird** [comment]
Thanks.  I upgraded to 10.x.  Now when I do `npm i @iota/client` I see this:

```
prebuild-install WARN install /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29 not found (required by /home/ryan/chrys/node_modules/@iota/client/build/Release/index.node)

 @iota/client@0.3.0 rebuild /home/ryan/chrys/node_modules/@iota/client
 npm run build:neon && node scripts/strip.js

 @iota/client@0.3.0 build:neon /home/ryan/chrys/node_modules/@iota/client
 neon build --release && node scripts/move-lib.js

neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @iota/client@0.3.0 build:neon: `neon build --release && node scripts/move-lib.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @iota/client@0.3.0 build:neon script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

```

I think GLIBC_2.29 is not available for my OS version.  I am on Ubuntu 18.  Looks like I might need to upgrade the OS to proceed.

**Comment by Thoralf-M** [comment]
Did you get it working?

**Comment by DayalMukati** [comment]
@Thoralf-M i am still getting below error.

I am having Node version 10.15.3. 
Kindly help.


neon ERR! spawn cargo ENOENT

Error: spawn cargo ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by Thoralf-M** [comment]
@DayalMukati do you have Rust installed?

**Comment by DayalMukati** [comment]
I was not having rust but installed it now. After rust installation I rerun the same cmd now i am getting below error.


error: failed to run custom build command for `neon-sys v0.8.2`

Caused by:
  process didn't exit successfully: `/Users/dayalmukati/Desktop/IOTA/iota-tutorial/node_modules/@iota/client/native/target/release/build/neon-sys-125e610d55b919d9/build-script-build` (exit code: 101)
  --- stdout
  Skipping node-gyp installation as part of npm install.
  added 98 packages from 73 contributors and audited 98 packages in 11.608s
  found 0 vulnerabilities


  --- stderr
  thread 'main' panicked at 'Failed to run "node-gyp configure" for neon-sys!
   Out: 
  > @ configure-release /Users/dayalmukati/Desktop/IOTA/iota-tutorial/node_modules/@iota/client/native/target/release/build/neon-sys-ee9375609ca836b0/out/native
  > node-gyp configure --verbose





error: build failed
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/Users/dayalmukati/Desktop/IOTA/iota-tutorial/node_modules/neon-cli/lib/target.js:98:27)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/dayalmukati/Desktop/IOTA/iota-tutorial/node_modules/neon-cli/lib/target.js:24:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Thoralf-M** [comment]
Maybe you need to have the requirements for node-gyp installed, see here https://github.com/nodejs/node-gyp#installation

**Comment by Thoralf-M** [comment]
Closing it, since there has been no comment for so long
