### ISSUE TITLE
Feature request: Java binding

### ISSUE THREAD

**Issue by jonasbark** [iotaledger-archive/iota.rs#501]
I saw there was a PR already for a Java binding but it was closed a while ago:
https://github.com/iotaledger/iota.rs/pull/84

Are there plans to reintroduce the Java bindings? I searched for it but found no 'official' information :)

**Comment by kwek20** [comment]
@jonasbark yes this is still planned! Unfortunately I had other priorities due to chrysalis so was not able to work on it yet. I plan on starting this on the weekend

**Comment by jonasbark** [comment]
Awesome! I'm available for testing if needed :)

**Comment by jonasbark** [comment]
Any news on this front? :)

**Comment by kwek20** [comment]
@jonasbark PR is ready!
