### ISSUE TITLE
dustAllowanceOutput() fails

### ISSUE THREAD

**Issue by xanpj** [iotaledger-archive/iota.rs#505]
## Bug description

using `dustAllowanceOutput()` instead of `output()` does not enable sending of transactions below 1 MIOTA.

Code:

```js
await client
          .message()
          .seed(seed)
          .accountIndex(0)
          .dustAllowanceOutput(address, 250000)
          .submit();
```

## Rust version

Which version of Rust are you running?

`node.js binding @iota/client 0.3.1`

## Version

Which version of the library are you using?

`node.js binding @iota/client 0.3.1`

## Hardware specification

What hardware are you using?

- Operating system: Mac OSX 10.15.7
- RAM:
- Cores:
- Device: Mac

## Steps To reproduce the bug

1. Run Code pasted above with a valid seed, address and client on chrysalis testnet

## Expected behaviour

The dustAllowanceOutput transaction succeeding.

## Actual behaviour

Error as described below.

## Errors

`
Error: ClientTask error: Client(DustError("Amount for SignatureLockedDustAllowanceOutput needs to be >= 1_000_000"))
`

Does this maybe have to do with the node not being up-to-date or did I maybe misunderstand the way SignatureLockedDustAllowanceOutputs work?
Is there a chance to prepare an easy to follow documentation for dust outputs besides [https://github.com/GalRogozinski/protocol-rfcs/blob/dust/text/0032-dust-protection/0032-dust-protection.md](https://github.com/GalRogozinski/protocol-rfcs/blob/dust/text/0032-dust-protection/0032-dust-protection.md)

**Comment by Thoralf-M** [comment]
`dustAllowanceOutput()` need >= 1 Mi, because this output will enable dust
You send dust with `output()`, but only if there is an dust allowance output on this address before, or in the same message like this 
```JS
    const messageId = await client.message()
        .seed(IOTA_SEED_SECRET)
        .dustAllowanceOutput('atoi1qqydc70mpjdvl8l2wyseaseqwzhmedzzxrn4l9g2c8wdcsmhldz0ulwjxpz', 1000000)
        .output('atoi1qqydc70mpjdvl8l2wyseaseqwzhmedzzxrn4l9g2c8wdcsmhldz0ulwjxpz', 1)
        .submit();
```

**Comment by xanpj** [comment]
Cheers, this is what I thought!

For reference:

The following activates an address for receiving dust:
```js
 .dustAllowanceOutput('atoi1qqydc70mpjdvl8l2wyseaseqwzhmedzzxrn4l9g2c8wdcsmhldz0ulwjxpz', 1000000)
 ```

And once an address has dust output allowance it can receive dust outputs such as:
```js
 .output('atoi1qqydc70mpjdvl8l2wyseaseqwzhmedzzxrn4l9g2c8wdcsmhldz0ulwjxpz', 1)
```

1) Can it receive infinite outputs after "dust activation"?
2) Is there a higher-level function to check if an address has dustOutputAllowance in @iota/client already?

Thanks in advance!

**Comment by Thoralf-M** [comment]
> Can it receive infinite outputs after "dust activation"?

No, it's dust allowance amount (amount of iotas, not amount of outputs) divided by 100_000 with a maximum of 100 dust outputs on one address in total
> Is there a higher-level function to check if an address has dustOutputAllowance in @iota/client already?

If you use getBalance() in the result is a `dust_allowed` field which says if you can send dust there or not

**Comment by xanpj** [comment]
> If you use getBalance() in the result is a dust_allowed field which says if you can send dust there or not

1) Thanks! I assume that flag reacts to the particularities of "dust allowance amount divided by 100_000", as in, calculates that on every `getBalance()`?

2) So micro transactions are not possible on IOTA anymore unless you prepare an address accordingly?

**Comment by Thoralf-M** [comment]
Yes for both, at least for Chrysalis, it might change with Coordicide

**Comment by xanpj** [comment]
Forgot a question:

> No, it's dust allowance amount (amount of iotas, not amount of outputs) divided by 100_000 with a maximum of 100 dust outputs on one address in total

Is the 100 dust outputs limit per "dust allowance output" or the total total of dust outputs on an address?

Thanks in advance!

**Comment by Thoralf-M** [comment]
100 is the total limit for one address
If you have 1 dust allowance output with 1 Mi you can have 10 dust outputs (1_000_000 / 100_000)
If you have 1 dust allowance output with 5 Mi you can have 50 dust outputs (5_000_000 / 100_000)
If you have 1 dust allowance output with 11 Mi you can have 100 dust outputs (11_000_000 / 100_000 would be 110, but 100 is the maximum)
If you have 2 dust allowance outputs with 1 Mi and 2 Mi you can have 30 dust outputs (1+2 = 3 Mi and 3_000_000/ 100_000 = 30)
If you have 2 dust allowance outputs with 10 Mi and 2 Mi you can have 100 dust outputs (10+2 = 12 Mi and 12_000_000/ 100_000 = 120, but 100 is the maximum)

Hope with that it's clear now
