### ISSUE TITLE
NodeJS  wrong type declarations

### ISSUE THREAD

**Issue by 0xrubes** [iotaledger-archive/iota.rs#515]
## Bug description

I encountered two wrong type declarations while working with the nodejs bindings:

## Version

Version: @iota/client 0.3.1

## Expected behaviour

Show correct typings of functions

## Actual behaviour

1)

`AddressGetter.get()` returns an array of strings and not as typed `[string, boolean][]`
Also, the [documentation ](https://github.com/iotaledger/iota.rs/tree/dev/bindings/nodejs#AddressGetter)states that it returns an array of `Address` instances, which is not the case.

![Screenshot_16](https://user-images.githubusercontent.com/44226748/115697179-9d3c5a00-a363-11eb-9540-0f3add18aec5.png)

2)
`IndexationPayload.index` is not a string, as its typed, but still a bytearray

![Screenshot_12](https://user-images.githubusercontent.com/44226748/115697838-3c615180-a364-11eb-9ba6-1cb67464d138.png)

**Comment by 0xrubes** [comment]
Also, when I compile a project that has the npm-package installed, I get some more errors:

![Screenshot_17](https://user-images.githubusercontent.com/44226748/115699291-d1187f00-a365-11eb-8bca-13f53f5ea684.png)

**Comment by alenhrga** [comment]
> 
> 
> Also, when I compile a project that has the npm-package installed, I get some more errors:
> 
> ![Screenshot_17](https://user-images.githubusercontent.com/44226748/115699291-d1187f00-a365-11eb-8bca-13f53f5ea684.png)

Same thing happens to me, it seems that `index.d.ts` file is missing an import for `MilestoneUTXOChanges`, and completely missing `Receipts` and `Treasury` classes.

@mmesar Temporary fix would be to ignore errors via `skipLibCheck` compiler option property in tsconfig.json:
```
{
  "compilerOptions": {
    "skipLibCheck": true
```
