### ISSUE TITLE
Support any base-url for node-endpoints

### ISSUE THREAD

**Issue by 0xrubes** [iotaledger-archive/iota.rs#527]
## Description

The clients require `/api/v1` - url endpoints, which currently makes it unable to communicate with permanodes. 

## Motivation

Endpoints should be dynamically adjustable, especially as the communication with permanodes is very important for queries of messages.

## Are you planning to do it yourself in a pull request?

Currently not

**Comment by louaykamel** [comment]
@Thoralf-M, I will say `iota.rs` should distinguish `permanode-endpoint` from a `regular node-endpoint`, as permanode api specs will keep evolving on long term.
