### ISSUE TITLE
NodeJS: Typed Objects should have attribute names in camelCase

### ISSUE THREAD

**Issue by 0xrubes** [iotaledger-archive/iota.rs#528]
## Description

The attribute names of type declarations should be written in proper camelCase instead of snake_case.

## Motivation

As camel case is the defacto standard for JS/TS developers, the nodejs-bindings should comply. Especially since the method names are already written in camel case

## Are you planning to do it yourself in a pull request?

Currently not

**Comment by Thoralf-M** [comment]
Which attributes do you mean?

**Comment by 0xrubes** [comment]
For example some of these:

![Screenshot_19](https://user-images.githubusercontent.com/44226748/116862585-478a6c00-ac05-11eb-92a3-b7cda3e7d9b4.png)
