### ISSUE TITLE
Python Mainnet Exception

### ISSUE THREAD

**Issue by FFGMP** [iotaledger-archive/iota.rs#529]
## Bug description

When trying to connect to the Mainnet it gives me an exception: 
> pyo3_runtime.PanicException: Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.

## Version

- Version: python-binding-v0.1.0

## Hardware specification

What hardware are you using?

- Operating system:
- Operating system: Windows 10 but tried on Ubuntu too.
- RAM: 8GB
- Cores: 4 

## Steps To reproduce the bug

```
NetworkVar = "Mainnet"

client = iota_client.Client(
    network=NetworkVar)
```

## Expected behaviour

Probably a connection to a loadbalancer on the Mainnet.

## Actual behaviour

It does nothing unless i remove the parameter.

## Errors

> pyo3_runtime.PanicException: Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.

**Comment by Lafudoci** [comment]
I have the same issue. It was totally fine on testnet , but got exception when switching to mainnet.

**Comment by bingyanglin** [comment]
Would you please try
```python
import iota_client

client = iota_client.Client(
    nodes_name_password=[['https://chrysalis-nodes.iota.org']], network="mainnet")
print(client.get_info())
```
by using the latest prebuilt python wheels (like from [this version](https://github.com/iotaledger/iota.rs/runs/2460549377) or newer)
Thank you.

**Comment by Lafudoci** [comment]
> Would you please try
> 
> ```python
> import iota_client
> 
> client = iota_client.Client(
>     nodes_name_password=[['https://chrysalis-nodes.iota.org']], network="mainnet")
> print(client.get_info())
> ```
> 
> by using the latest prebuilt python wheels (like from [this version](https://github.com/iotaledger/iota.rs/runs/2460549377) or newer)
> Thank you.

That  adding `nodes_name_password` works for me.

```
{
    'nodeinfo': {
        'name': 'HORNET', 'version': '1.0.1', 'is_healthy': True, 'network_id': 'chrysalis-mainnet', 'bech32_hrp':
        'iota', 'min_pow_score': 4000.0, 'messages_per_second': 62.1, 'referenced_messages_per_second': 54.6, 'referenced_rate':
        87.92270531400966, 'latest_milestone_timestamp': 1619768747, 'latest_milestone_index': 15200,
            'confirmed_milestone_index': 15200, 'pruning_index': 0, 'features': ['PoW']
    }, 'url': 'https://chrysalis-nodes.iota.org'
}
```

**Comment by bingyanglin** [comment]
Great! Then please close this issue if there is no other errors related to the `mainnet` setting after more tests,
