### ISSUE TITLE
Can't import Python's iota_client on Linux Ubuntu 18.04

### ISSUE THREAD

**Issue by EasonC13** [iotaledger-archive/iota.rs#557]
## Bug description

Can't use Python's iota_client on Linux Ubuntu 18.04

## Rust version

Which version of Rust are you running?

- Rust version: n/a
- Python Version: 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0]

## Version

Which version of the library are you using?

I use the package from [this commit](https://github.com/iotaledger/iota.rs/actions/runs/665254286)

## Hardware specification

What hardware are you using?

for Ubuntu
- Operating system: Ubuntu 18.04
- RAM: 32GB
- Cores: 8 cores

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Download `linux-iota-client-py3.8-wheel` file from [this commit](https://github.com/iotaledger/iota.rs/actions/runs/665254286)
2. unzip and pip install it.
3. open Python with the following code.

```
import iota_client

client = iota_client.Client()
```

## Expected behaviour

I hope it works as the js version. (No Error)

## Actual behaviour

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-10-5ba5747d7db7> in <module>
----> 1 import iota_client
      2 
      3 # client will connect to testnet by default
      4 client = iota_client.Client()
      5 print(client.get_info())

~/anaconda3/lib/python3.8/site-packages/iota_client/__init__.py in <module>
----> 1 from .iota_client import *

ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/eason/anaconda3/lib/python3.8/site-packages/iota_client/iota_client.abi3.so)
```

> This is the first time I open Issue there. If I make any mistake, please tell me. Thank you.

**Comment by Thoralf-M** [comment]
GLIBC_2.29 is required, either you install it manually yourself or maybe update Ubuntu to a newer version
