### ISSUE TITLE
Rename project name to iota.rs

### ISSUE THREAD

**Issue by wusyong** [iotaledger-archive/iota.rs#6]
Since it's now under official Github, maybe it's a good time to rename it to be same as other language libraries like iota.js, iota.go etc. Perhaps revise README.md is also needed? 🤔

**Comment by njaremko** [comment]
While this library is under the iotaledger account, it is not yet official. Renaming at this point is unnecessary and would likely cause confusion. I've cleaned up the README a bit.

**Comment by wusyong** [comment]
I see. As README is well informed, I think I can close this for now.
