### ISSUE TITLE
Add dust management

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [iotaledger-archive/iota.rs#611]
## Description

Integrate a dust management into the client/wallet to abstract this away from the user:

one function get_dust_address() returns a valid dust address if funds are sufficient

## Motivation

I currently implement it myself and thought this could be a useful feature in the standard library.
This is how it could roughly look like:

```python
class DustManager():

    def __init__(self):

        if DUST_SEED is None:
            raise Exception('Canot allow dust without giving a dust seed')
        
        self.seed = DUST_SEED

        self.client = iota_client.Client(nodes_name_password=[[NODE_URL]])

        self.balance = self.client.get_balance(self.seed)

        self.dust_address = self.client.get_unspent_address(self.seed)[0]

        if self.balance < IOTA_DUST:

            LOG.error('Not enough funds to allow dust!')

            LOG.error('Please transfer at least %s IOTA to address %s', (IOTA_DUST, self.dust_address))

            # sets ALLOW_DUST to false gloablly
            disable_dust()          

        self.number_of_dust_transactions = int(self.balance / 100_000)

        if not self.__is_dust_enabled():

            self.__refresh_dust()

    def transaction_received(self):

        self.number_of_dust_transactions -= 1

        if self.number_of_dust_transactions < 1 or not self.__is_dust_enabled():
            self.__refresh_dust()

    def __refresh_dust(self):
        # max out dust allowance with entire balance
        self.balance = self.client.get_balance(self.seed)

        if self.balance < IOTA_DUST:

            disable_dust()

            return 

        # send the entire balance to the dust address wit dust allowance
        message = self.client.message(
        seed=self.seed,
        dust_allowance_outputs=[
            {
                'address': self.dust_address,
                'amount': self.balance,
            }
            ]
        )

        LOG.info("Dust is now allowed for %s" % self.dust_address)

        self.client.retry_until_included(message_id = message['message_id'])
        
        # reset counter
        self.number_of_dust_transactions = int(self.balance / 100_000)

    def __is_dust_enabled(self):

        address_balance_pair = self.client.get_address_balances([self.dust_address])[0]

        if address_balance_pair['dust_allowed']:

            return True

        return False

    def get_dust_address(self):

        if ALLOW_DUST:

            return self.dust_address

        LOG.warning('No dust allowed!')

        return None

```

## Requirements

1.  get_dust_address() function for the user
2.  have a dust manager in the background as descibed above

## Open questions (optional)

It may be useful to implement this feature in the base rust library rather than directly in the binding?

## Are you planning to do it yourself in a pull request?

No. I don't feel comfortable enough in rust to do it myself

**Comment by Thoralf-M** [comment]
This looks very specific to me, since basically all you need to get an address with dust allowance is 
```
dust_address = self.client.get_unspent_address(self.seed)[0]
message = self.client.message(
        seed=self.seed,
        dust_allowance_outputs=[
            {
                'address': dust_address,
                'amount': 1_000_000,
            }
        ]
)
```
And sending the total balance to this address may not be desired by everyone
Also not sure for what is `transaction_received` and btw `self.number_of_dust_transactions = int(self.balance / 100_000)` should be limited to 100, since 100 is the maximum of dust outputs an address can have

**Comment by F-Node-Karlsruhe** [comment]
Yes, i took my specific code and pasted it here to give a rough idea what a dust manager may do.

Even though the mentioned operation in your answer is relatively straight forward, it may be a bit too much overhead when it has to be done for every dust transaction you want to receive or you have to remember which of your addresses is the dust address and how many dust outputs are already on there.

In my opinion dust became more user friendly if you just had to call one function to get the latest, working dust address.

So the main tasks that were taken over by a background dust management are:
- keep track of the dust outputs
- refresh the dust address if neccessary (equivalent to merging dust outputs)
- initially create dust address when demanded

**Comment by F-Node-Karlsruhe** [comment]
I created a python version of a dust manager. I think it might be useful to have it embedded directly into the client library.
At least it is now available for python ... as soon as I find out how to publish to pip :D

Feedback appreciated :)

https://github.com/F-Node-Karlsruhe/iota-dust-manager

**Comment by bingyanglin** [comment]
Thanks for the good work. For iota.rs we aim to provide a stateless low-level client library, and your dust manager will force the user to maintain the states of dust addresses. I think what you provided is a specific application which shows a good example of how to use the client library to complete a specific task. Note that we have a [wallet.rs](https://github.com/iotaledger/wallet.rs) which is stateful package with a standardised interface for developers to build applications involving IOTA value transactions.

**Comment by F-Node-Karlsruhe** [comment]
The dust management actually works stateless as it always reuses the same address (maybe a questionable practice).
I close the issue here. Maybe we will come back to it later.
As I mainly work with python, I can use my python implementation.
