### ISSUE TITLE
Copy codeblock always copies also the `$` and makes copy / paste unusable

### ISSUE THREAD

**Issue by Phyloiota** [iotaledger-archive/iota.rs#612]
## Bug description

Using the function to copy a code block copies the whole code including the `$` in every line, which leads to an error by pasting it in a Terminal.
This is an annoying bug in a lot of Repos.

## Steps To reproduce the bug

Use the copy button and paste the code into VSCode or any other Terminal
![image](https://user-images.githubusercontent.com/77154511/125071246-a085ed00-e0eb-11eb-98cb-4dacb85b370f.png)
If i use the copy function, this gets pasted in my Terminal:

$ cd iota.rs/bindings/java
$ ./gradlew examples:basic-app:test --info

**Comment by Phyloiota** [comment]
Also present in this repos:
https://github.com/iotaledger/wasp
https://github.com/iotaledger/wallet.rs
https://github.com/iotaledger/zephyr-client-sdk
https://github.com/iotaledger/prometheus
https://github.com/iotaledger/ledger-iota-app
https://github.com/iotaledger/webhookd

Maybe more in older Repos also...

**Comment by Thoralf-M** [comment]
For iota.rs updated here https://github.com/iotaledger/iota.rs/commit/cd9c31c454a75bab772c17509f9a148af7135da7

**Comment by bingyanglin** [comment]
Already fixed and merged.
