### ISSUE TITLE
v0.6.4 and v0.6.5 of the @iota/client wrapper cannot get address balance in the mainnet

### ISSUE THREAD

**Issue by Impulse87** [iotaledger-archive/iota.rs#625]
## Bug description

Cannot get address balances, it throws: 
`Error: ClientTask error: Client(Json(Error("missing field ledgerIndex", line: 1, column: 134)))`
Example mainnet: https://prnt.sc/1fcypoz

Testnet does work with the same version and dependencies.
Example testnet: https://prnt.sc/1fcy7es

## Version

Which version of the library are you using?
@iota/client -> https://www.npmjs.com/package/@iota/client

- Version number, commit, or branch: 
v0.6.4 & v0.6.5

## Hardware specification

What hardware are you using?
- Operating system: debian buster (docker container) -> see project Dockerfile: https://gitlab.com/uniqbit-public/iota/iota-payment-observer
- RAM: varying it's deployed in a kubernetes cluster
- Cores: varying it's deployed in a kubernetes cluster
- Device: varying it's deployed in a kubernetes cluster

## Steps To reproduce the bug

1. connect to mainnet
2. create a seed and get it's first best iota1XXXX address
3. try to get the address balance

OR
1. clone this project: https://gitlab.com/uniqbit-public/iota/iota-payment-observer
2. modify package.json @iota/client version to e. g. v0.6.5
2. install dependencies: `npm i`
3. run the project: `npm start`
4. call example url: http://localhost:4100/ipo/#/transaction?data=%7B%22value%22:2000000%7D&theme=light&lang=de
5. see the console log

## Expected behaviour

it should return a JSON object with the address and a balance

## Actual behaviour

it throws an error: 
`Error: ClientTask error: Client(Json(Error("missing field ledgerIndex", line: 1, column: 134)))`

## Errors

see above.

**Comment by Thoralf-M** [comment]
This `ledgerIndex` field was added in Hornet 1.0.2 as you can see in your screenshots the nodeinfo for the mainnet node you're connected to is 1.0.1, that's why the field is missing

**Comment by Impulse87** [comment]
so it will be automatically solved when the mainnet gets upgraded to 1.0.2?

**Comment by Thoralf-M** [comment]
The mainnet itself doesn't care which version is used, but the node you use needs to be updated or you use an older version of the client that doesn't expect this field

**Comment by Impulse87** [comment]
I'm using the loadbalancer target address https://chrysalis-nodes.iota.org for mainnet connection.

**Comment by Thoralf-M** [comment]
I asked devops to update it, but don't know when it will happen

**Comment by Impulse87** [comment]
so long i'm happy using v0.6.3 :)

**Comment by Thoralf-M** [comment]
The nodes got updated a few days ago
