### ISSUE TITLE
[Python bindings] Improve examples / tests

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#663]
## Description

- Add more examples;
- Add missing tests.

**Comment by bingyanglin** [comment]
## Testing Check List
### Full node API
- [x] get_health()
- [x] get_info()
- [x] get_peers()
- [x] get_tips()
- [x] post_message()
- [x] get_output()
- [x] get_address_balance()
- [x] get_address_outputs()
- [x] find_outputs()
- [x] get_milestone()
- [x] get_milestone_utxo_changes()
- [x] get_receipts()
- [x] get_receipts_migrated_at()
- [x] get_treasury()
- [x] get_included_message()

### HIgh-level API
- [x] message
- [x] get_output_amount_and_address
- [x] prepare_transaction
- [x] sign_transaction
- [x] finish_message
- [x] get_message_metadata
- [x] get_message_data
- [x] get_message_raw
- [x] get_message_children
- [x] get_message_id
- [x] get_message_index
- [x] find_messages
- [x] get_unspent_address
- [x] get_addresses
- [x] get_balance
- [x] get_address_balances
- [x] generate_mnemonic
- [x] mnemonic_to_hex_seed
- [x] find_inputs
- [x] bech32_to_hex
- [x] hex_to_bech32
- [x] hex_public_key_to_bech32_address
- [x] is_address_valid
- [x] retry
- [x] retry_until_included
- [x] consolidate_funds
- [x] reattach
- [x] promote

### MQTT
- [x] subscribe_topic
- [x] subscribe_topics
- [x] unsubscribe
- [x] unsubscribe_topics
- [x] disconnect

**Comment by bingyanglin** [comment]
## Example Check List
- [x] consolidation
- [x] create_max_dust
- [x] custom_inputs
- [x] custom_parent
- [x] custom_payload
- [x] dust
- [x] get_fund
- [x] indexation
- [x] message_time
- [x] mnemonic
- [x] multiple_outputs
- [x] peers
- [x] quorum
- [x] search_address
- [x] send_all
- [x] split_all
- [x] split_outputs_single_address
- [x] storage
- [x] transaction
- [x] txspam

**Comment by bingyanglin** [comment]
Close the issue because all the testing/examples are done.
