### ISSUE TITLE
wallet.rs fails to compile because sub dependency of iota.rs iota-client

### ISSUE THREAD

**Issue by tuddman** [iotaledger-archive/iota.rs#667]
## Bug description

A sub-sub dependency of outdated `rumqttc` library makes the wallet fail to compile:

```
<home>/.cargo/registry/src/github.com-1ecc6299db9ec823/async_io_stream-0.2.0/src/lib.rs:1:40
  |
1 | #![cfg_attr( nightly, feature(doc_cfg, external_doc) )]
  |                                        ^^^^^^^^^^^^ feature has been removed
  |
  = note: use #[doc = include_str!("filename")] instead, which handles macro invocations

For more information about this error, try `rustc --explain E0557`.
error: could not compile `async_io_stream` due to previous error
```

iota.ra -> iota-client.rs `1.0.1` -> rumqttc `v0.5.0` -> ws_stream_tungstenite `v0.4.0` -> async_io_stream `v0.2.0`

Fix:  Update https://github.com/iotaledger/iota.rs/blob/dev/iota-client/Cargo.toml#L45  to `0.8.0`

Downstream dependencies are fixed, too, including `async_io_stream` as of [this commit](https://github.com/najamelan/async_io_stream/commit/9f0605c2ca78df42ef43cea67c7babf018585941#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759)

## Rust version

- Rust version:  rustc 1.56.0-nightly (371f3cd3f 2021-09-02

## Version

- indirectly from `dev` branch of wallet.rs: 1.0.1

## Hardware specification

- Operating system:  OSX

## Steps To reproduce the bug

1.   make a simple rust project with wallet.rs as a dependency in `Cargo.toml`
```
[dependencies]
iota-wallet = { git = "https://github.com/iotaledger/wallet.rs", branch = "dev" }
```
2.  `cargo update`
3.  `cargo run`
4.  compilation error :(

## Expected behaviour

compiles

## Actual behaviour

Compilation error.

**Comment by Thoralf-M** [comment]
If you use rustc 1.54.0 it should still work, the error is only there with nightly

Updating rumqttc to 0.8 doesn't fix it, we need to wait for the next release or use is with a git revision (waiting for a review of a PR in iota.rs)

**Comment by tuddman** [comment]
correct.  thanks @Thoralf-M !  switching to use `1.54.0` `stable`  eliminated this compilation error.
