### ISSUE TITLE
[Task]: Provide support for decoding indexation payload

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#678]
## Description

Currently, the users have to write their own implementation for decoding the indexation payload. For instance, see [this](https://github.com/iotaledger/iota.rs/blob/wasm/bindings/wasm/native/examples/07_get_message_data.js#L18). 

Since, this seems like a common use case, it would be good to provide support from the library for this. 

## Motivation

For the convenience of users. 

## Requirements

`decodeIndexationPayload(payload, encodingScheme = 'utf8')` should be exposed from the library. 

## Open questions (optional)

N/A

## Are you planning to do it yourself in a pull request?

No.

**Comment by samuel-rufi** [comment]
Fixed by https://github.com/iotaledger/iota.rs/pull/911
