### ISSUE TITLE
[Task]: Integrate Rudra with GitHub actions

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#679]
## Description

[Rudra](https://github.com/sslab-gatech/Rudra) is a nice tool for detecting common undefined behaviours in Rust programs. Would be good to have it setup as part of the library workflow. 

## Motivation

Would be good to have a static analysis of the changes submitted with each PR.

**Comment by rajivshah3** [comment]
Awaiting #686 because it fixes issues with compilation on the nightly toolchain, which is required for Rudra

**Comment by laumair** [comment]
@rajivshah3 Looks like #686 was merged.

**Comment by jyhi** [comment]
_Rudra does not support edition 2021 yet_ (<https://github.com/sslab-gatech/Rudra#known-issues>), which is another blocker of this issue.

**Comment by thibault-martinez** [comment]
I will close this for now as rudra doesn't support workspaces (we have one), and edition 2021 (we are using it).
