### ISSUE TITLE
[Bug]: JS-binding problem in react-native

### ISSUE THREAD

**Issue by IoTAdri** [iotaledger-archive/iota.rs#691]
## Bug description

When using in our code:
```
import { ClientBuilder } from "@iota/client";
```
we get an error:
```
Unable to resolve module ../build/Release/index.node from C:\Users\A3\code\rncourse\iota\first\node_modules\@iota\client\lib\index.js:

None of these files exist:
  * node_modules\@iota\client\build\Release\index.node(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  * node_modules\@iota\client\build\Release\index.node\index(.native|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json)
  11 |   AddressGetter,
  12 |   BalanceGetter
> 13 | } = require('../build/Release/index.node')
     |              ^
  14 |
  15 | global.TextEncoder = require("util").TextEncoder;
  16 |
```

## Version

Which version of the library are you using?
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@iota/client": "^2.0.0",
    "expo": "~42.0.1",
    "expo-status-bar": "~1.0.4",
    "react": "16.13.1",
    "react-dom": "16.13.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz",
    "react-native-web": "~0.13.12"
  },
  "devDependencies": {
    "@babel/core": "^7.9.0"
  },
  "private": true
}

```

## Hardware specification

What hardware are you using?

- Operating system: Windows 10
- RAM: 32G
- Cores: 8

With Android emulator as a virtual device.

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1.  start a standard react native project
2.  add: import { ClientBuilder } from "@iota/client";
3. 

## Errors

![image](https://user-images.githubusercontent.com/16754039/134779593-50db6d2d-b660-47a6-bd7d-f9962cc9b726.png)

![image](https://user-images.githubusercontent.com/16754039/134779602-94bd0772-dd84-4e4f-9347-a6573ea59f6d.png)

**Comment by Thoralf-M** [comment]
I think the issues comes from the neon version we use for the binding, updating it in wallet.rs fixed the issue. We want to do the same for iota.rs, but it requires some more work, related to <https://github.com/iotaledger/iota.rs/issues/662>
The Wasm binding will be released soon, you could try with the test package if that works for you (the name will change, when we release it, but the functions will probably not change anymore) <https://www.npmjs.com/package/test-iota-client-wasm>
API reference: <https://github.com/iotaledger/iota.rs/blob/098dd71add85cfaecd03fce13d04e0d547ac2eb0/bindings/wasm/native/docs/api-reference.md>
Examples: <https://github.com/iotaledger/iota.rs/tree/098dd71add85cfaecd03fce13d04e0d547ac2eb0/bindings/wasm/native/examples>

**Comment by IoTAdri** [comment]
> The Wasm binding will be released soon, you could try with the test package if that works for you (the name will change, when we release it, but the functions will probably not change anymore) https://www.npmjs.com/package/test-iota-client-wasm

![image](https://user-images.githubusercontent.com/16754039/134812621-ecd788e1-4c6a-4e4a-8e65-14695ad3d90a.png)
Do you have info on how about i can use this in react native?

**Comment by Thoralf-M** [comment]
No, haven't tested it yet, but as I wrote the package name you need to use now is `test-iota-client-wasm`, the other one isn't published yet

**Comment by jyhi** [comment]
Is this resolved in some way?

**Comment by IoTAdri** [comment]
no... we are still looking for a (good) way to use the rust-bindings in react-native.

**Comment by laumair** [comment]
@IoTAdri What exact problems are you facing when you try to use the wasm package in react native environment?

**Comment by laumair** [comment]
Also related: https://github.com/iotaledger/iota.rs/issues/755
