### ISSUE TITLE
[Task]: Add a guide / example for using the library with Electron

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#754]
### Task description

Add a guide / example for using the WASM bindings with an Electron app. The integration of library with major application frameworks should be really straightforward and we should have reference examples / guides for that. 

### Requirements

- Create an example of using WASM bindings in an Electron app under [examples/](https://github.com/iotaledger/iota.rs/tree/dev/bindings/wasm/examples);
- The Electron app should accept a valid IOTA address through text field and should be able to make a transaction to the address (a reference example can be looked at [here](https://github.com/iotaledger/iota.rs/blob/dev/bindings/wasm/examples/09_transaction.js));
- The example should have a detailed documentation with information not limited to:
         - Step by step process of how to install wasm bindings in an Electron app;
         - Versions of Electron / WASM bindings for which the example is valid;
         - Possible issues that users may run into while installation with their mitigation strategy

### Acceptance criteria

The example should be complete in a sense that anybody wanting to use wasm bindings in an Electron app should be able to look at the reference example and the documentation to be able to use it in their apps. 

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by thibault-martinez** [comment]
Won't be done because not possible with the node.js bindings and there are no plans for wasm bindings at the moment. This could be done by the iota.js team in the future.
