### ISSUE TITLE
[Task]: Add a guide / example for using the library with Capacitor

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#756]
## Description

Add a guide / example for using the WASM bindings with capacitor. 

## Motivation

The integration of library with major application frameworks should be really straightforward and we should have reference examples / guides for that. 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thibault-martinez** [comment]
Won't be done because not possible with the node.js bindings and there are no plans for wasm bindings at the moment. This could be done by the iota.js team in the future.
