### ISSUE TITLE
[Task]: Add a guide / example for configuring the library with webpack and rollup

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#757]
## Description

Add a guide / example for configuring the WASM bindings with webpack and roll up.  

## Motivation

A guide would be helpful for users wanting to use the library in their web applications. Common issues that can possibly occur during the integration can be documented in the guide so that it is straightforward for the consumers to use this library in their applications. 

## Are you planning to do it yourself in a pull request?

Maybe.

**Comment by thibault-martinez** [comment]
Won't be done because not possible with the node.js bindings and there are no plans for wasm bindings at the moment. This could be done by the iota.js team in the future.
