### ISSUE TITLE
[Task]: Ledger (hardware wallet) support 

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#758]
## Description

It would be good to have ledger support in the library. The signing process in [wallet.rs](https://github.com/iotaledger/wallet.rs) can be taken as a reference. 

## Motivation

Not a pressing requirement but would be nice to have this in the library. 

## Requirements

TBD

## Are you planning to do it yourself in a pull request?

No.

**Comment by Thoralf-M** [comment]
Closed for https://github.com/iotaledger/iota.rs/issues/873
