### ISSUE TITLE
README Instructions for Java Bindings Need Improvement

### ISSUE THREAD

**Issue by carpenterdev** [iotaledger-archive/iota.rs#765]
## Bug description

I'm following the IOTA Rust library README. The cargo run --example 01_get_info worked fine. But now I've dropped into https://github.com/iotaledger/iota.rs/tree/dev/bindings/java, and am trying to build the rust library, which I think is named native.jar, but the README doesn't exactly mention the name. I've done: cd iota.rs/bindings/java/native, and then cargo build. A lot of building is done, and it ends without mentioning any error, but when I look in the iota.rs/bindings/java/native directory there's no native.jar.

## Steps To reproduce the bug

1. Go to Rust Java Bindings README - https://github.com/iotaledger/iota.rs/tree/dev/bindings/java 
2. Follow "Build the rust library" step 1 for Java in a Win10 Bash Shell using $ cd iota.rs/bindings/java/native
3. Follow "Build the rust library" step 2 for Java in a Win10 Bash Shell using $ cargo build

## Expected behaviour

I expected a native.jar to be created. I checked all dirs below iota.rs/bindings/java and didn't find one.

The README should provide more steps, and information. Please realize that README's should be written for inexperienced users, and should document all steps, possible errors, and fixes. At this point I don't know if the build process has errors, or my lack of experience is preventing me from understanding what's to be created.

## Actual behaviour

The cargo build did much processing, without error. The native.jar was not built. Nothing appeared to be built.

## Errors

No Errors from $ cargo build 
I am new to cargo and rust, so I am unsure what to expect or how to debug.

**Comment by laumair** [comment]
@carpenterdev Thank you for reporting and apologies for the late response. 

I tried to reproduce this following the steps you were taking and I faced the same issue. I agree the documentation also needs some clarity. 

We will update the documentation.

/cc @kwek20

**Comment by hkoci** [comment]
I was having issues with building the jar as well and the issue lies with not specifying the release profile parameter - I found this out in the [wiki documentation](https://wiki.iota.org/iota.rs/libraries/java/getting_started).

The GitHub documentation does not specify that you need this param, but compiling without the release profile will use the dev profile, which does not generate the native.jar (iota-client-java v0.1.0) library atm.

`cargo build --release` instead of `cargo build`

Hope this helps any other newbies like me :)

**Comment by Gerriko** [comment]
I too am having problems using cargo build --release (same issue faced using just cargo build).
Context. I'm using Linux Mint / Ubuntu 20.04
I have java-11-openjdk-amd64

First error was easily resolved as I had not set the JAVA_HOME environment variable in .profile/.bashrc... probably worth noting that JAVA_HOME required in documentation.

The next error, I cannot resolve. I get an error message saying "thread 'main' panicked at 'Could not find header jni.h', native/build.rs:71:80"

So where is jni.h?

**Comment by MarkMk1** [comment]
Hello :)

Built it as is trying to follow the guidelines as closely as I could, tried to use generated jar in an android project, can successfully create ClientConfig object but on attempting to create the Client, it crashes with a FileNotFound error, as it can't find the shared library which is visibly present in the jar.

Any existing android integrations I can look into?
