### ISSUE TITLE
[Task]: Add tests for verifying correct address derivation from seed

### ISSUE THREAD

**Issue by laumair** [iotaledger-archive/iota.rs#790]
## Description

We lack tests that verify that address derivation is at par across implementations and bindings i.e., rust implementation and (java, nodejs, python) bindings. We should add them to be sure every implementation has correct address derivation. 

## Motivation

Extensive tests like these are needed to be confident about deterministic address derivation across all implementations. 

## Requirements

For a set of mnemonics, ensure they lead to deterministic addresses for different indexes. 

- Python — @bingyanglin;
- Java — @kwek20;
- Rust — @Thoralf-M;
- NodeJS — @laumair;
- Wasm — @laumair 

The mnemonics / seeds and expected addresses should be shared between all tests. 

**Tests should cover both derivations from mnemonics and also from hex seeds.**

## Open questions (optional)

Happy to hear if there are any other similar test scenarios that should be covered. 

## Are you planning to do it yourself in a pull request?

Yes — for nodejs bindings.

**Comment by laumair** [comment]
https://github.com/iotaledger/iota-sdk/issues/73

**Comment by Thoralf-M** [comment]
Test for Rust: https://github.com/iotaledger/iota.rs/pull/791

**Comment by bingyanglin** [comment]
Add global test vector json: #https://github.com/iotaledger/iota.rs/pull/791/commits/b95eb59c527387f993d4e1c3cbabacf00aa79bdf

**Comment by bingyanglin** [comment]
Add python testing for mnemonic address generation: #https://github.com/iotaledger/iota.rs/pull/791/commits/b7a565673e1778b8c96b406458d2a16b6afb409d

**Comment by Thoralf-M** [comment]
For stardust we should add more tests also for different coin types, account/address indexes and public/internal addresses and for the different signer types

**Comment by laumair** [comment]
NodeJS: https://github.com/iotaledger/iota.rs/pull/791/commits/9aef4a5e611087a5caa70dd0efe3e4e235080438

**Comment by laumair** [comment]
WASM: https://github.com/iotaledger/iota.rs/pull/791/commits/52bdc90b49a1ffbc8898c598127577389476da98
