### ISSUE TITLE
[Task]: Extend Stronghold Signer functionality

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#834]
### Task description

It should be able to use the stronghold file for backups, so we need functions to store data inside and also read it again.
For the password to improve security we also want to add the option for an auto clearing from the memory after x seconds, but also need functions to set it again later and also to manually clear it.

### Requirements

1. Add a function to store bytes at a location
2. Add a function to get bytes that are stored at a location
3. Add auto clearing of the password (spawn a thread which does this, similar to https://github.com/iotaledger/wallet.rs/blob/213140abefbe6aec0d0d15d5a151b408e75fcc1e/src/stronghold.rs#L209), if the password is cleared we should also emit an event for that, so applications can know that
4. Add an optional field to set the timeout during initialisation, if nothing is provided, it should be disabled
5. Add a function to set the password (needed to unlock it, if the password got cleared before)
6. Add a function to clear the password

### Acceptance criteria

We want to use it in wallet.rs for backups and improve the security for applications like Firefly

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jyhi** [comment]
I think 3 should be done by the user of iota.rs (wallet.rs, say); we only do 6 (only provide an interface for clearing the password) to keep iota.rs stateless.

**Comment by Thoralf-M** [comment]
Why wouldn't it be stateless anymore if you put the password inside of an Arc<Mutex<>> you can share with the password clearing thread?

**Comment by jyhi** [comment]
A timer is a state... and does iota.rs have an event system for us to emit something?

**Comment by jyhi** [comment]
Nevermind, I've changed my mind, we can do this.
