### ISSUE TITLE
add core functionality to WASM binding

### ISSUE THREAD

**Issue by huhn511** [iotaledger-archive/iota.rs#86]
Suggestion:

Make `create_address` and `create_addresses` functions public available. 
https://github.com/iotaledger/iota.rs/blob/81657433b7736d98ac27b61c230841767769e339/bindings/wasm/src/lib.rs#L88

So the API is more open for developers and they can create addresses from an index.

**Comment by Thoralf-M** [comment]
Outdated, because we don't have wasm bindings anymore
