### ISSUE TITLE
trytes_converter only handles ASCII

### ISSUE THREAD

**Issue by mayjs** [iotaledger-archive/iota.rs#89]
Is there a reason why we can't just convert arbitrary binary data to trytes? The whole trytes_converter module seems overly complex to me, why do we have to use manual lookup tables from ascii to numerical values instead of just using `str.bytes` and converting? The latter change would also allow us to convert utf-8 to trytes.

**Comment by wusyong** [comment]
It's more a historical reason that it's is ASCII only. I'm actually preparing a module to support more encodings (with utf8 as default).

**Comment by cvarley100** [comment]
We will not be making additional changes to the existing mainnet implementation. The current focus is Chrysalis.
