### ISSUE TITLE
[Task]: Install required packages in workflows

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#896]
### Task description

Currently the CI fails with `error: failed to run custom build command for `hidapi v1.3.4` see https://github.com/iotaledger/iota.rs/runs/5864138132?check_suite_focus=true
I think that's because for the ledger dependencies we need to install 
```
    - name: Install required packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libudev-dev libusb-1.0-0-dev
```
(from wallet.rs https://github.com/iotaledger/wallet.rs/blob/a058c76620e1a0953713f386c0d4436536b442b5/.github/workflows/build-and-test.yml#L51)

### Requirements

Install required packages

### Acceptance criteria

Workflows don't fail because of missing dependencies

### Creation checklist

- [X] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jyhi** [comment]
Fixed in #951.
