### ISSUE TITLE
essence.hash()

### ISSUE THREAD

**Issue by cao148** [iotaledger-archive/iota.rs#916]
I want to know is there any way to achieve this through js?
[https://github.com/iotaledger/bee/blob/mainnet-develop/bee-message/src/payload/transaction/essence/mod.rs#L33](url)

**Comment by Thoralf-M** [comment]
Currently it's not possible, but could be added
What would you expect as input? The transaction essence?

**Comment by cao148** [comment]
@Thoralf-M I hope js can provide this method of essence.hash()

**Comment by thibault-martinez** [comment]
Will be done through https://github.com/iotaledger/iota.rs/issues/920
