### ISSUE TITLE
[Bug]: Compiling error on branch dev

### ISSUE THREAD

**Issue by szeslite** [iotaledger-archive/iota.rs#962]
### Issue description

error[E0599]: the function or associated item `new` exists for struct `CurlPBatchHasher<T1B1Buf>`, but its trait bounds were not satisfied
   --> C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\bee-pow-0.2.0\src\providers\miner.rs:116:55
    |
116 |         let mut hasher = CurlPBatchHasher::<T1B1Buf>::new(HASH_LENGTH);
    |                                                       ^^^ function or associated item cannot be called on `CurlPBatchHasher<T1B1Buf>` due to unsatisfied 
trait bounds
    |
   ::: C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\bee-ternary-0.5.2\src\t1b1.rs:102:1
    |
102 | pub struct T1B1Buf<T: Trit = Btrit>(Vec<T>);
    | -------------------------------------------- doesn't satisfy `T1B1Buf: bee_ternary::raw::RawEncodingBuf`
    |
   ::: C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\iota-crypto-0.9.2\src\hashes\ternary\curl_p\batched\mod.rs:31:1
    |
31  | pub struct CurlPBatchHasher<B: RawEncodingBuf> {
    | ----------------------------------------------
    | |
    | doesn't satisfy `CurlPBatchHasher<T1B1Buf>: Clone`
    | doesn't satisfy `CurlPBatchHasher<T1B1Buf>: Default`
    | doesn't satisfy `CurlPBatchHasher<T1B1Buf>: Digest`
    | doesn't satisfy `CurlPBatchHasher<T1B1Buf>: digest::Reset`
    | doesn't satisfy `CurlPBatchHasher<T1B1Buf>: digest::Update`
    | doesn't satisfy `_: digest::fixed::FixedOutput`
    |
    = note: the following trait bounds were not satisfied:
            `T1B1Buf: bee_ternary::raw::RawEncodingBuf`
            `CurlPBatchHasher<T1B1Buf>: digest::Update`
            which is required by `CurlPBatchHasher<T1B1Buf>: Digest`
            `CurlPBatchHasher<T1B1Buf>: digest::fixed::FixedOutput`
            which is required by `CurlPBatchHasher<T1B1Buf>: Digest`
            `CurlPBatchHasher<T1B1Buf>: digest::Reset`
            which is required by `CurlPBatchHasher<T1B1Buf>: Digest`
            `CurlPBatchHasher<T1B1Buf>: Clone`
            which is required by `CurlPBatchHasher<T1B1Buf>: Digest`
            `CurlPBatchHasher<T1B1Buf>: Default`
            which is required by `CurlPBatchHasher<T1B1Buf>: Digest`
            `&CurlPBatchHasher<T1B1Buf>: digest::Update`
            which is required by `&CurlPBatchHasher<T1B1Buf>: Digest`
            `&CurlPBatchHasher<T1B1Buf>: digest::fixed::FixedOutput`
            which is required by `&CurlPBatchHasher<T1B1Buf>: Digest`
            `&CurlPBatchHasher<T1B1Buf>: digest::Reset`
            which is required by `&CurlPBatchHasher<T1B1Buf>: Digest`
            `&CurlPBatchHasher<T1B1Buf>: Default`
            which is required by `&CurlPBatchHasher<T1B1Buf>: Digest`
            `&mut CurlPBatchHasher<T1B1Buf>: digest::Update`
            which is required by `&mut CurlPBatchHasher<T1B1Buf>: Digest`
            `&mut CurlPBatchHasher<T1B1Buf>: digest::fixed::FixedOutput`
            which is required by `&mut CurlPBatchHasher<T1B1Buf>: Digest`
            `&mut CurlPBatchHasher<T1B1Buf>: digest::Reset`
            which is required by `&mut CurlPBatchHasher<T1B1Buf>: Digest`
            `&mut CurlPBatchHasher<T1B1Buf>: Clone`
            which is required by `&mut CurlPBatchHasher<T1B1Buf>: Digest`
            `&mut CurlPBatchHasher<T1B1Buf>: Default`
            which is required by `&mut CurlPBatchHasher<T1B1Buf>: Digest`

error[E0277]: the trait bound `T1B1Buf: bee_ternary::raw::RawEncodingBuf` is not satisfied
   --> C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\bee-pow-0.2.0\src\providers\miner.rs:116:26
    |
116 |         let mut hasher = CurlPBatchHasher::<T1B1Buf>::new(HASH_LENGTH);
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `bee_ternary::raw::RawEncodingBuf` is not implemented for `T1B1Buf`
    |
note: required by a bound in `CurlPBatchHasher`
   --> C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\iota-crypto-0.9.2\src\hashes\ternary\curl_p\batched\mod.rs:31:32
    |
31  | pub struct CurlPBatchHasher<B: RawEncodingBuf> {
    |                                ^^^^^^^^^^^^^^ required by this bound in `CurlPBatchHasher`

error[E0308]: mismatched types
  --> C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\bee-pow-0.2.0\src\score.rs:52:26
   |
52 |         self.curl.digest(self.pow_input.as_slice())
   |                          ^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `bee_ternary::Trits`, found struct `Trits`
   |
   = note: expected reference `&bee_ternary::Trits`
              found reference `&Trits`
   = note: perhaps two different versions of crate `bee_ternary` are being used?

error[E0308]: mismatched types
  --> C:\Users\12146\.cargo\registry\src\github.com-1ecc6299db9ec823\bee-pow-0.2.0\src\score.rs:52:9
   |
33 |     pub fn hash(&mut self, bytes: &[u8]) -> TritBuf<T1B1Buf> {
   |                                             ---------------- expected `TritBuf` because of return type
...
52 |         self.curl.digest(self.pow_input.as_slice())
   |
   = note: expected struct `TritBuf`
              found struct `bee_ternary::TritBuf`
   = note: perhaps two different versions of crate `bee_ternary` are being used?

Some errors have detailed explanations: E0277, E0308, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `bee-pow` due to 4 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed

### Version

dev

### Expected behaviour

Compile success

### Actual behaviour

Compile failed

### Can the issue reliably be reproduced?

Yes

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thoralf-M** [comment]
It's related to https://github.com/iotaledger/bee/issues/1360
For now as workaround you could pin iota-crypto
```
iota-crypto = { version = "=0.9.1" }
```

**Comment by thibault-martinez** [comment]
@szeslite It should be fixed now, can you try again and close the issue if needed ? Thanks.

**Comment by thibault-martinez** [comment]
Closing this as we think it's been fixed. Feel free to reopen if that's not the case.
