### ISSUE TITLE
[Task]: Add .zeroize() to mnemonic and stronghold password

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#988]
### Task description

Add .zeroize() to mnemonic and stronghold password in store_mnemonic() and also to the other methods in the message_interface (also remove the MessageType in the Response for that, like we did for wallet.rs here https://github.com/iotaledger/wallet.rs/pull/1019/commits/530d3e440688fd5a1755328b0fccce116db02a22)

### Requirements

Stronghold password and mnemonic is zeroized when possible

### Acceptance criteria

N/A

### Creation checklist

- [ ] I have assigned this task to the correct people
- [X] I have added the most appropriate labels
- [X] I have linked the correct milestone and/or project

**Comment by jyhi** [comment]
Fixed by #995.
