### ISSUE TITLE
Add a method to stronghold which returns if the key is available

### ISSUE THREAD

**Issue by Thoralf-M** [iotaledger-archive/iota.rs#992]
## Description

Method should return if `key: Arc<Mutex<Option<Zeroizing<Vec<u8>>>>>,` is_some()

## Motivation

Users should have an option to know if they still need to set the password, so they don't get an error because it's missing when they do an action

## Requirements

1. Add new public method to get if the key is set

## Are you planning to do it yourself in a pull request?

No.

**Comment by jyhi** [comment]
Fixed by #995.
